# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_check_update = false

  # Master
  config.vm.define "m1" do |m1|
    m1.vm.hostname = "demo-m1"
    m1.vm.network "private_network", ip: "192.168.56.101"

    m1.vm.provision "shell", path: "setup.sh"
  end

  # Worker 1
  config.vm.define "w1" do |w1|
    w1.vm.hostname = "demo-w1"
    w1.vm.network "private_network", ip: "192.168.56.102"

    w1.vm.provision "shell", path: "setup.sh"
    w1.vm.provision "shell", path: "rke2/agent/setup.sh"
  end

  # Worker 2
  config.vm.define "w2" do |w2|
    w2.vm.hostname = "demo-w2"
    w2.vm.network "private_network", ip: "192.168.56.103"

    w2.vm.provision "shell", path: "setup.sh"
    w2.vm.provision "shell", path: "rke2/agent/setup.sh"
  end

  # Common Settings
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = 2
  end
  
  config.vm.synced_folder "/etc/ssl/certs", "/etc/ssl/certs"
end
